# Hipster Application Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: hipster
  labels:
    istio-injection: enabled
  #annotations:
  #  configmanagement.gke.io/cluster-selector: selector-destiny