# Banking Application Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: bank-app
  labels:
    istio-injection: enabled
  annotations:
    configmanagement.gke.io/cluster-selector: cis-dev-config-selector