# helloworld Application Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    istio-injection: enabled
  annotations:
    configmanagement.gke.io/cluster-selector: destiny-selector
