# Bookinfo Application Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  labels:
    istio-injection: enabled
  annotations:
    configmanagement.gke.io/cluster-selector: cis-prod-config-selector
